name: CICD GitHub workflow BTD
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn clean compile
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Run Tests with Maven
        run: mvn -B test --file pom.xml
      - name: ServiceNow DevOps Unit Test Results
        uses: ServiceNow/servicenow-devops-test-report@main
        with:
          devops-integration-token: '${{ secrets.SN_DEVOPS_TOKEN }}'
          instance-url: '${{ secrets.SN_INSTANCE_URL }}'
          tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
          job-name: Test
          context-github: '${{ toJSON(github) }}'
          xml-report-filename: target/surefire-reports/testng-results.xml
  registerArtifact:
    name: Register Artifact
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow DevOps Register Artifact
        uses: ServiceNow/servicenow-devops-register-artifact@main
        with:
          devops-integration-token: '${{ secrets.SN_DEVOPS_TOKEN }}'
          instance-url: '${{ secrets.SN_INSTANCE_URL }}'
          tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
          job-name: Register Artifact
          context-github: '${{ toJSON(github) }}'
          artifacts: >-
            [ {      "name": "app-devops.jar", "version": "1.${{
            github.run_number }}", "semanticVersion": "1.${{ github.run_number
            }}.0", "repositoryName": "${{ github.repository }}" } ]
  registerPackage:
    name: registerArtifact
    needs: registerArtifact
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow DevOps Register Package
        uses: ServiceNow/servicenow-devops-register-package@main
        with:
          devops-integration-token: '${{ secrets.SN_DEVOPS_TOKEN }}'
          instance-url: '${{ secrets.SN_INSTANCE_URL }}'
          tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
          context-github: '${{ toJSON(github) }}'
          artifacts: >-
            [ { "name": "app-devops.jar", "version": "1.${{ github.run_number
            }}", "semanticVersion": "1.${{ github.run_number }}.0",
            "repositoryName": "${{ github.repository }}" } ]
          package-name: app-devops-change-velocity.war
          job-name: Register Package
          
  sonarScan:
   name: 'Sonar Scan'
   # if: ${{ github.ref != 'refs/heads/main' }}
   needs: registerPackage
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v5.1.0
   - name: ServiceNow DevOps Sonar Scan Results
   # You may pin to the exact commit or the version.     
     uses: ServiceNow/servicenow-devops-sonar@v5.1.0
     with:
         # ServiceNow Instance URL
         instance-url: ${{ secrets.SN_INSTANCE_URL }}
         # Devops Integration Token
         # devops-integration-user-name: '${{ secrets.SN_DEVOPS_USER }}'
         # devops-integration-user-password: '${{ secrets.SN_DEVOPS_PASSWORD }}'
         devops-integration-token: ${{ secrets.SN_DEVOPS_TOKEN }}
         # Orchestration Tool Id
         tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
         # Github Context
         context-github: ${{ toJSON(github) }}
         # Display Name of the Job
         job-name: 'Sonar Scan'
         # Sonar Host URL
         sonar-host-url: ${{ secrets.SONAR_URL }}
         # Sonar Project Key
         sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
  deploy:
    name: Deploy
    needs: sonarScan
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment scripts
        run: echo 'Deployment step in progress...'
  ServiceNowDevOpsChange:
    needs: deploy
    runs-on: ubuntu-latest
    name: ServiceNow DevOps Change
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@main
        with:
          devops-integration-token: '${{ secrets.SN_DEVOPS_TOKEN }}'
          instance-url: '${{ secrets.SN_INSTANCE_URL }}'
          tool-id: '${{ secrets.SN_ORCHESTRATION_TOOL_ID }}'
          context-github: '${{ toJSON(github) }}'
          job-name: ServiceNow DevOps Change
          change-request: >-
            {"setCloseCode":"true","attributes":{"short_description":"Automated
            Software Deployment","description":"Automated Software
            Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018"}}
